spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "This is the contact file for webhooks accounts env"
  info:
    name: "Keshav - QA lead"
    email: "keshavbajaj@gmail.com"
  contact:
    +919873554224
